model:
  type: 'simclr'
  mlp_dim: 256
  infonce_weight: 1.0
  vicreg_weight: 1.0
  barlowtwins_weight: 0
  representations_losses: [true, false, false]
  embeddings_losses: [false, true, false]
training:
  batch_size: 256
data:
  train: '/media/user/Samsung_T5/sslsv/data/vox2_npy_list'
  wav_augment:
    enable: true
