model:
  type: 'simclr'
  enable_mlp: False  # Projector 조절
  mlp_dim: 1024
  infonce_weight: 1.0
  vicreg_weight: 1.0
  barlowtwins_weight: 0.0
  representations_losses: [false, True, false] # infonce / Vicreg / barlowtwins
  embeddings_losses: [True, false, false]
training:
  batch_size: 512
  max_samples: 500
data:
  train: 'data/voxceleb2_train_list'
  #train: '/media/nextgen/Samsung_T5/sslsv/data/sm_npy_list'
  wav_augment:
    enable: False
    musan: False
    rir: False
