model:
  type: 'simclr'
  enable_mlp: false
  infonce_weight: 0.0
  vicreg_weight: 1.0
  barlowtwins_weight: 0.0
  representations_losses: [false, True, false]
training:
  batch_size: 128
  max_samples: 500
data:
  train: '/media/nextgen/Samsung_T5/sslsv/data/vox2_total_npy_list'
  wav_augment:
    enable: true
